# Generated by Django 6.0 on 2026-04-25 15:41

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='contactEnquiry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('email', models.CharField(max_length=60)),
                ('subject', models.CharField(max_length=100)),
                ('service', models.CharField(choices=[('cleaning', 'Cleaning'), ('plumbing', 'Plumbing'), ('electrical', 'Electrical'), ('ac', 'AC Repair')], max_length=50)),
                ('message', models.TextField()),
            ],
        ),
    ]
